name: dev-cd

on:
# manual trigger
  workflow_dispatch:

jobs:
  build:
    if: github.repository == 'crustio/crust-frontend'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and push docker
        run: |
          docker build -t gavfu/crust-web:latest .
          docker login -u ${{ secrets.DOCKER_HUB_DEV_USER_NAME }} -p ${{ secrets.DOCKER_HUB_DEV_PASSWORD }}
          docker push gavfu/crust-web:latest
